trigger:
- none

variables:
- group: AKSVariables

pool:
  name: Azure-VM

resources:
  - repo: self  

name: $(date:yyyyMMdd)$(rev:.r)

stages:
- stage: CI
  displayName: 'CI Stage'

  jobs:
  - job: Build
    displayName: 'Build and Test'
    steps:

    - checkout: self
      clean: true
      fetchDepth: 0 

    - task: SonarCloudPrepare@2
      inputs:
        SonarCloud: 'SonarCloud-Con'
        organization: 'pranavtripathi'
        scannerMode: 'Other'
        extraProperties: |
          sonar.projectKey=pranavtripathi_AKS-DockerDeployment
          sonar.projectName=AKS-DockerDeployment

    - task: Maven@4
      displayName: 'Build and Test with Sonar Code analysis'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean verify sonar:sonar'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        codeCoverageToolOption: 'JaCoCo'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: true
        isJacocoCoverageReportXML: true
        codeCoverageRestoreOriginalPomXml: true
        sqMavenPluginVersionChoice: 'latest'

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/target'
        Contents: '**/*.jar'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/target'
        OverWrite: true
        
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    
    - task: Docker@2
      inputs:
        containerRegistry: 'ACR-connection'
        repository: 'aks-deploy-javaapp'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        tags: 'latest'
