trigger:
- none

variables:
- group: AKSVariables

pool:
  name: Azure-VM

resources:
  - repo: self  

name: $(date:yyyyMMdd)$(rev:.r)

stages:
- stage: CI
  displayName: 'CI Stage'

  jobs:
  - job: Build
    displayName: 'Build and Test'
    steps:

    - checkout: self
      clean: true
      fetchDepth: 0 

    - script: |
        java -version
      displayName: 'Check Java Version'

    - script: |
        echo "Java Home: $JAVA_HOME"
        echo "Java Path: $PATH"
      displayName: 'Check Java Path'

    - task: SonarCloudPrepare@2
      inputs:
        SonarCloud: 'SonarCloud-Con'
        organization: 'pranavtripathi'
        scannerMode: 'Other'
        extraProperties: |
          sonar.projectKey=pranavtripathi_AKS-DockerDeployment
          sonar.projectName=AKS-DockerDeployment

    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean verify sonar:sonar'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        codeCoverageToolOption: 'JaCoCo'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: true
        isJacocoCoverageReportXML: true
        sqMavenPluginVersionChoice: 'specificVersion'
        sqMavenPluginVersion: '3.9.0'

    # - task: SonarCloudAnalyze@2
    #   inputs:
    #     jdkversion: 'JAVA_HOME'
           
    # - task: PublishBuildArtifacts@1
    #   inputs:
    #     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    #     ArtifactName: 'drop'
    #     publishLocation: 'Container'