trigger:
- none

variables:
- group: AKSVariables

pool:
  name: Azure-VM

resources:
  - repo: self  

name: $(date:yyyyMMdd)$(rev:.r)

stages:
- stage: CI
  displayName: 'CI Stage'

  jobs:
  - job: Build
    displayName: 'Build and Test'
    steps:

    - checkout: self
      clean: true
      fetchDepth: 0

    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '11'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
        
    - task: SonarCloudPrepare@2
      inputs:
        SonarCloud: 'SonarCloud-Con'
        organization: 'pranavtripathi'
        scannerMode: 'Other'
        extraProperties: |
          sonar.projectKey=pranavtripathi_AKS-DockerDeployment
          sonar.projectName=AKS-DockerDeployment

    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean verify sonar:sonar'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        codeCoverageToolOption: 'JaCoCo'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: true
        isJacocoCoverageReportXML: true
        sqMavenPluginVersionChoice: 'pom'

    - task: SonarCloudAnalyze@2
      inputs:
        jdkversion: 'JAVA_HOME'
           
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'