trigger:
- none

variables:
- group: AKSVariables

pool:
  name: Azure-VM

resources:
  - repo: self  

name: $(date:yyyyMMdd)$(rev:.r)

stages:
- stage: CI
  displayName: 'CI Stage'

  jobs:
  - job: Build
    displayName: 'Build and Test'
    steps:

    - checkout: self
      clean: true
      fetchDepth: 0 

    - task: SonarCloudPrepare@2
      inputs:
        SonarCloud: '$(SonarCloud)'
        organization: '$(SonarOrganization)'
        scannerMode: 'Other'
        extraProperties: |
          sonar.projectKey=$(SonarProjectKey)
          sonar.projectName=$(SonarProjectName)

    - task: Maven@4
      displayName: 'Build and Test with Sonar Code analysis'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean verify sonar:sonar'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        codeCoverageToolOption: 'JaCoCo'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: true
        isJacocoCoverageReportXML: true
        codeCoverageRestoreOriginalPomXml: true
        sqMavenPluginVersionChoice: 'latest'

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/target'
        Contents: '**/*.jar'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/target'
        OverWrite: true
        
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    
    - task: Docker@2
      inputs:
        containerRegistry: '$(ContainerRegistry)'
        repository: '$(Repository)'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        tags: 'latest'

    - script: |
        trivy image $(ContainerRegistry)/$(Repository):latest
      displayName: 'Scan Docker Image with Trivy'

- stage: CD
  displayName: 'Deploy Stage'
  dependsOn: CI

  jobs:
  - job: Deploy
    displayName: 'Deploy to AKS'
    steps:
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: '$(KubernetesServiceEndpoint)'
        namespace: 'default'
        command: 'apply'
        arguments: '-f deployment.yaml'

    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: '$(KubernetesServiceEndpoint)'
        namespace: 'default'
        command: 'apply'
        arguments: '-f service.yaml'
