apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: javawebapp
        image: acraksdeploy.azurecr.io/aks-deploy-javaapp:latest
        ports:
        - containerPort: 8080